FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy required config files
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 6007
EXPOSE 6007

# Command to run the application
CMD ["npm", "start"]
