FROM node:18

# Create app directory
WORKDIR .

# Copy required config files
COPY package*.json ./

COPY tsconfig.json ./

COPY .env ./

COPY .next ./.next


# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 5000
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]