FROM node:18

# Create app directory
WORKDIR /src

# Copy package.json and package-lock.json (if available)
COPY src/package*.json ./

# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 5000
EXPOSE 5000

# Command to run the application
CMD ["npm", "start"]
