FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy required config files
COPY package*.json ./

COPY tsconfig.json ./

COPY .env ./

# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 5000
EXPOSE 5000

# Command to run the application
CMD ["npm", "start"]
