FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy required config files
COPY package*.json ./

COPY tsconfig.json ./

RUN apk add --update --no-cache python3 build-base gcc && ln -sf /usr/bin/python3 /usr/bin/python
# Install app dependencies
RUN npm install

# Copy app source to the image
COPY . .

# Expose the app on port 5001
EXPOSE 5001

# Command to run the application
CMD ["npm", "start"]
